services:
  app:
    build: ./app
    container_name: log4shell-app
    ports:
      - "8080:8080"
    networks:
      - log4shell-net

  ldap-server:
    build: ./ldap
    container_name: log4shell-ldap
    networks:
      - log4shell-net

  http-server:
    image: python:3.11-slim
    container_name: log4shell-http
    working_dir: /poc
    volumes:
      - ./poc:/poc
    command: python3 -m http.server 8000
    networks:
      - log4shell-net

networks:
  log4shell-net:
    driver: bridge
